### ISSUE TITLE
大神 dein的build怎么弄  装了 但没装好 不知道哪里出问题了 

### ISSUE THREAD

**Issue by huayue369** [iamcco/git-p.nvim#2]

**Comment by iamcco** [comment]
如果已经装了可以手动执行下 `:call sran#util#install()`

或者用下面的安装

``` vim
call dein#add('iamcco/sran.nvim', {
                \ 'build': 'yarn install'
                \})
call dein#add('iamcco/git-p.nvim')
```

**Comment by huayue369** [comment]
谢谢了  大神我个人很喜欢你的插件 感觉你对于neovim新功能跟进的非常快  我非常喜欢你这插件演示里出现提示不会因为提示推动代码区窗口 像ale 和 coc.vim的提醒功能都会推动窗口 这点体验不是很好 对于他们不知道你会不会有很好的替代方案

**Comment by iamcco** [comment]
@huayue369 coc.nvim 已经支持浮窗提示了，应该不会推动窗口（最新的 coc+最新的 neovim）。ale 我已经不用了。如果有部分 lsp 没有支持的语言，我目前是 https://github.com/iamcco/diagnostic-languageserver + linter 配合 coc 在用。

**Comment by huayue369** [comment]
恩 很不好意思 gitp我貌似并没有装成功可能 我设置有问题 我刚刚自学编程 确实很菜   关于languageserver我之前就有关注 你在gitter里面有向别人推荐过 很想用 但无赖本人能力很差  看了下非常复杂  只能忍痛遗憾 。。。我一直有关注你的动态。。

**Comment by iamcco** [comment]
有报什么错么？你用的什么版本的 neovim

**Comment by huayue369** [comment]
最新版  就是更改了没有提示  设置方面我什么都没该 就把你的配置示例复制了一下  是不是需要自己配置什么  对git不是很熟  只会基本操作。。。
、、、
" use custom highlight for blame virtual text
" change GitPBlameLineHi to your highlight group
highlight link GitPBlameLine GitPBlameLineHi
" format blame virtual text
" hash: commit hash
" account: commit account name
" date: YYYY-MM-DD
" time: HH:mm:ss
" ago: xxx ago
" zone: +xxxx
" commit: commit message
" lineNum: line number
"let g:gitp_blmae_format = '    %{account} * %{ago}'
" use custom diff sign
let g:gitp_add_sign = '■'
let g:gitp_modify_sign = '▣'
let g:gitp_delete_top_sign = '▤'
let g:gitp_delete_bottom_sign = '▤'
let g:gitp_delete_top_and_bottom_sign = '▤'
"使用自定义高亮显示差异符号
"将GitPAddHi GitPModifyHi GitPDeleteHi更改为突出显示组
highlight link GitPAdd                GitPAddHi
highlight link GitPModify             GitPModifyHi
highlight link GitPDeleteTop          GitPDeleteHi
highlight link GitPDeleteBottom       GitPDeleteHi
highlight link GitPDeleteTopAndBottom GitPDeleteHi 
、、、

**Comment by iamcco** [comment]
你怎么安装的？

**Comment by huayue369** [comment]
[[plugins]]
repo = 'iamcco/sran.nvim'
build = 'yarn install'

[[plugins]]
repo = 'iamcco/git-p.nvim'
depends = 'sran.nvim'
hook_add = 'source ~/.config/nvim/rc/plugins/git-p.vim'

**Comment by iamcco** [comment]
`:message` 看下报什么错

**Comment by huayue369** [comment]
没报错  刚刚又出现提示  是不是需要什么命令启动啊  再进改动就没提示了

**Comment by iamcco** [comment]
打开一个 git 项目文件，然后 `:echo b:gitp_diff_state` 看下显示什么

**Comment by huayue369** [comment]
Undefined variable: b:gitp diff stateUndefined variable: b:gitp diff state

**Comment by iamcco** [comment]
这样的话应该是插件没起来，而且没报错，很奇怪

**Comment by huayue369** [comment]
。。。。是啊  无解

**Comment by huayue369** [comment]
还能抢救下吗？

**Comment by iamcco** [comment]
在你的 vim 配置添加：

``` vim
let $NVIM_SRAN_LOG_FILE = expand('~/sran-nvim.log')
let $NVIM_SRAN_LOG_LEVEL = 'debug'
```

然后打开一个 git 项目的文件，然后到 `~/` 目录下把 `sran-nvim.log` 文件发上来我看下。


不过我通过下面的配置，使用 dein 是没有问题的：

``` vim
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('iamcco/sran.nvim', {
        \ 'build': 'yarn install'
        \})
  call dein#add('iamcco/git-p.nvim')

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

**Comment by huayue369** [comment]
恩 谢谢大神  这会又可以使用了
感觉跟我的coc。nvim同一个插件冲突 真巧

**Comment by huayue369** [comment]
大神 你的插件都挺好用的  但你好像没他们推广的多啊。。

**Comment by iamcco** [comment]
> 感觉跟我的coc。nvim同一个插件冲突 真巧

和 coc 冲突了怎么解决的？我这里也同时用了 coc，貌似没遇到过冲突，如果是 vim 的话昨天刚修了一个和 coc 的冲突，neovim 还没遇到过。

> 大神 你的插件都挺好用的 但你好像没他们推广的多啊。。

需要 neovim 最新版才能用，感觉用的人不会多的

**Comment by huayue369** [comment]
和coc没冲突 和另外一个小众插件冲突
把冲突插件删除就ok了
 我这份配置用的另外一个大佬的 我输入这个命令echo dein#update()🈶️️会好一下 最后还是在他的帮助下找到冲突插件才解决问题  
dein对我来说还是太复杂了 之前用的plug  感觉简单好多  我感觉装插件的速度也比dein快 但江湖传言dein跟牛点 。。。。也没用明白。。。

**Comment by iamcco** [comment]
感觉 dein 优势并不多，而且弄得有点复杂
