### ISSUE TITLE
Support for smaller hash len

### ISSUE THREAD

**Issue by Mariappan** [iamcco/git-p.nvim#4]
Hi

Thanks for this wonderful plugin. gitp_blame feature with neovim is awesome. 
Finally getting features which are available in IDE till now. 😄 

I have one small feature request. While displaying hash, currently the entire hash is displayed. Would it be possible to add an option to display only shorter version of the commit hash ?

Feel free to close this, if you feel this is unnecessary bloat. 

Once again, thanks for this plugin. Now I can also show off my development environment to guys using Code or Atom.

**Comment by iamcco** [comment]
I have add
1.  `%{name:number}` to get first `number` of characters.
2. `%{name:number:number}` to get range of characters.

**Comment by Mariappan** [comment]
I have tried the following 
`let g:gitp_blame_format = '    %{hash:6}  %{account} * %{ago}'`

But instead of substring, I am getting blame as follows:
`highlight link GitPDeleteBottom       GitPDeleteHi     %{hash:6}  You * a moment ago `

**Comment by Mariappan** [comment]
Sorry did not notice the latest commit. 
Thanks a lot 😄 👍
