### ISSUE TITLE
Feature request: allow cursor to move into the popup

### ISSUE THREAD

**Issue by voldikss** [iamcco/git-p.nvim#5]
- 当 diff 的文本行数很多时，显示不了全部内容，此时可以让光标进入 popup 窗口上下移动查看全部的改动。

- 有时需要拷贝 popup 窗口里面的内容。

建议增加“再按一次 <Leader>d 进入 popup 窗口”，类似 [git-messenger.vim](https://github.com/rhysd/git-messenger.vim#commands) 那种

P.S. 插件很好用！

**Comment by iamcco** [comment]
更新下，增加了diff 窗口显示的时候，再次按快捷键会跳到 diff 窗口，再次按关闭窗口

**Comment by voldikss** [comment]
试了下没问题，感谢大佬！
感觉给 popup window 绑定 q 键退出会更方便 🙈

**Comment by iamcco** [comment]
> 感觉给 popup window 绑定 q 键退出会更方便 🙈

加了

**Comment by voldikss** [comment]
感谢大佬！
