### ISSUE TITLE
启动后报错

### ISSUE THREAD

**Issue by xaljer** [iamcco/git-p.nvim#6]
- Neovim v0.4.0-737
- Windows 10
```
Plug 'iamcco/sran.nvim', { 'do': { -> sran#util#install() } }
Plug 'iamcco/git-p.nvim'
```
<img width="774" alt="Snipaste_2019-05-11_10-23-02" src="https://user-images.githubusercontent.com/8309631/57563988-8f3fd980-73d7-11e9-879b-2bd8f7038c2a.png">

**Comment by iamcco** [comment]
重新手动执行下 `:call sran#util#install()`，或者 到插件目录下执行 `yarn install`

**Comment by xaljer** [comment]
`:call sran#util#install()`后仍然会报错，要`yarn install`才行，这是vim-plug的问题还是？能解决吗？
另外我发现插件的功能似乎没有正常工作，比如我设置了`let g:gitp_blame_virtual_text = 1`，但所在行并没有显示，通过`<Plug>(git-p-i-blame)`触发也没有。

**Comment by iamcco** [comment]
`:call sran#util#install()` 不行有可能是网络问题，他需要下载一个预编译包。blame 没有显示的话你是打开的 git 管理的项目文件吗？还有你用的什么版本的 nvim?

**Comment by xaljer** [comment]
哦，但`:call sran#util#install()`后会有成功的提示。
关于blame，我发现其实是可以显示的，只是光标移动到一行后要差不多5秒后才能显示出来，没有像vscode那种即时显示的效果，所以我刚才以为有问题。这是性能问题还是策略问题？

**Comment by iamcco** [comment]
估计下载脚本有什么bug，慢那个设置 `set updatetime=300`，设置越小显示越快

**Comment by xaljer** [comment]
哦哦，抱歉没看到你FAQ里写的，blame的显示非常帅，谢谢你的插件。另外还有个小问题，这个状态栏显示是怎么弄的啊？
<img width="1115" alt="Snipaste_2019-05-11_12-59-33" src="https://user-images.githubusercontent.com/8309631/57565257-0a5fba80-73ed-11e9-876c-0de8f665dfd6.png">

**Comment by iamcco** [comment]
如果用 lightline 可以看下我这个 https://github.com/iamcco/dotfiles/blob/master/nvim/viml/plugins.config/lightline.vim.vim#L42 ，就是监听 `GitPDiffAndBlameUpdate` 自动事件，然后判断 `b:gitp_diff_state` 存不存在，存在就拿 `b:gitp_diff_state` 里面的字段更新 statusline

**Comment by xaljer** [comment]
所以airline支持吗？

**Comment by iamcco** [comment]
支持，airline怎么设置的就按照那个来，需要的信息都有了

**Comment by xaljer** [comment]
感谢，我自己来研究一下。
