### ISSUE TITLE
month in blame message is out of range

### ISSUE THREAD

**Issue by xaljer** [iamcco/git-p.nvim#7]
<img width="777" alt="Snipaste_2019-05-14_22-46-36" src="https://user-images.githubusercontent.com/8309631/57707624-816dab00-769a-11e9-9510-f3f41535dec9.png">

如图所示，月份信息溢出了。

**Comment by iamcco** [comment]
修复了，月份那个搞成了小时

**Comment by xaljer** [comment]
验证已修复，赞！
